languages = {
    'Afrikaans': 'af-ZA',
    'Amharic': 'am-ET',
    'Armenian': 'hy-AM',
    'Azerbaijani': 'az-AZ',
    'Indonesian': 'id-ID',
    'Malay': 'ms-MY',
    'Bengali': 'bn-IN',
    'Czech': 'cs-CZ',
    'Danish': 'da-DK',
    'German': 'de-DE',
    'English': 'en-US',
    'Spanish': 'es-ES',
    'Filipino': 'fil-PH',
    'French': 'fr-FR',
    'Gujarati': 'gu-IN',
    'Italian': 'it-IT',
    'Kannada': 'kn-IN',
    'Hungarian': 'hu-HU',
    'Malayalam': 'ml-IN',
    'Marathi': 'mr-IN',
    'Nepali': 'ne-NP',
    'Portuguese': 'pt-PT',
    'Romanian': 'ro-RO',
    'Swedish': 'sv-SE',
    'Tamil': 'ta-IN',
    'Telugu': 'te-IN',
    'Vietnamese': 'vi-VN',
    'Urdu': 'ur-IN',
    'Greek': 'el-GR',
    'Russian': 'ru-RU',
    'Hebrew': 'he-IL',
    'Arabic': 'ar-IL',
    'Hindi': 'hi-IN',
    'Mandarin': 'cmn-Hant-TW',
    'Japanese': 'ja-JP',
}
lang_opt = ['Afrikaans', 'Amharic', 'Armenian', 'Azerbaijani', 'Indonesian', 'Malay', 'Bengali', 'Czech', 'Danish', 'German', 'English', 'Spanish', 'Filipino', 'French', 'Gujarati', 'Italian', 'Kannada', 'Hungarian', 'Malayalam', 'Marathi', 'Nepali', 'Portuguese', 'Romanian', 'Swedish', 'Tamil', 'Telugu', 'Vietnamese', 'Urdu', 'Greek', 'Russian', 'Hebrew', 'Arabic', 'Hindi', 'Mandarin', 'Japanese']
